lib/backport.js
=> Fix global variable in for loop

lib/comment.js
Working:
- stable
- stable-3.4.x
- aiei3-ae
- stable_123
- a
- 1
Non working (intended):
- ##$$#
=> Obey also branches with - or _

index.js, lib/backport.js, lib/pr.js
=> Copy over labels from backported PR

lib/backport.js, lib/pr.js
=> Set milestone for backport PR

index.js, lib/commits.js, lib/pr.js
=> Update deprecated method calls with their replacement

app.yml
@rullzer Could you check with your app permissions on Github, because I guess you changed it there. I noticed this during setup of a new app.
=> Update the app permissions to have all needed ones

lib/git.js
Github is checking the user name.
See https://github.com/skjnldsv/npmbuildbot/blob/6c398eb92933967dbe775d2fcdf1129b515748c7/lib/git.js#L7
@rullzer
=> Set proper user to appear as the correct bot in the commits

index.js, lib/backport.js, lib/comment.js, lib/pr.js
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>
```
/backport to stable18
/backport 1564a2c to stable18
/backport 1564a2c,52feca3 to stable18
```
fix #95
cc @christophwurst @tobiasKaminsky @juliushaertl
=> Allow to provide array of commits to backport

lib/backport.js, lib/pr.js
@nickvergessen @christophwurst @rullzer @tobiasKaminsky
=> Fix conflicts message in pr body

lib/backport.js, lib/pr.js
@tobiasKaminsky @rullzer @MorrisJobke
=> Use additions/deletions to check for conflicts

README.md
Signed-off-by: Jonas <jonas@freesources.org>
=> Add basic documentation to README.md

lib/pr.js
This is hopefully helpful for everyone new to the concept of "backporting manually".
=> feat: Show manual backport instructions

lib/backport.js, lib/pr.js
- You cannot use `newPrId` before it is known and not `-1`
- Fixed the reviews array
=> Fix conflict check

lib/backport.js
Bigger picture: resolving conflicts is not always trivial. Sometimes it can be done with a re-apply of the git commit, other times it's fully manual. Sending people to the documentation and showing the manual backport process may already help understand the issue. Ideally we also add more detailed instructions for how to resolve those conflicted PRs.
=> feat(github): Add link to backport docs for conflicting PRs

lib/backport.js, lib/pr.js
It might help us understand see if the bot failed on a git(hub) operation or has internal errors.
=> feat: Print the name of the backport error

lib/pr.js
```
08:19:08.787Z ERROR probot: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
at Object.backportFailed (/app/lib/pr.js:137:34)
at module.exports (/app/lib/backport.js:137:19)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
=> fix: error name undefined

src/gitUtils.ts
https://github.com/simple-git-js/simple-git/#git-clean
=> fix: git clean syntax

src/backport.ts, src/gitUtils.ts
Signed-off-by: skjnldsv <skjnldsv@protonmail.com>
=> fix(backportbot): handle cleanup and diff failures

src/index.ts, src/payloadUtils.ts
=> feat: Respond to friendly humans

src/backport.ts, src/constants.ts, src/gitUtils.ts, src/index.ts, src/nextcloudUtils.ts
also fix https://github.com/nextcloud/backportbot/issues/685
=> fix: use commit title if only one commit is specified
